### ISSUE TITLE
UI Prototypes 

### ISSUE THREAD

**Issue by sadafgauba** [sgauba2/Fitness-Tracker-App#13]
Welcome page

<img width="1438" alt="Screen Shot 2022-03-07 at 11 08 32 PM" src="https://user-images.githubusercontent.com/93011134/157177190-1e52a25e-0251-4648-8f81-71fced86696b.png">

Login Page

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/93011134/157177285-f98cb381-41f2-4668-b312-55bc31d9ab8b.png">

Sign Up Page

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/93011134/157177380-e4534af6-2c8b-4269-903c-140120f03683.png">

Home Page

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/93011134/157177575-5f9bcb1c-2500-4943-8a3d-9b98401481ac.png">

Calorie Intake Log Page

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/93011134/157177670-f5da41fa-5682-43d2-ac92-572cb7c089f0.png">

Calorie Intake Form Page 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/93011134/157177749-383fbd02-d8eb-4ed4-b9e3-80027cdfe870.png">

**Comment by sadafgauba** [comment]
These is how the application will look like.
Also, all the buttons I have added work and take the user to the respective pages (i.e. the "Back" button on calorie intake log page takes user back to home page when clicked, etc.)

**Comment by sadafgauba** [comment]
Once professor's feedback / grade for HW7 is published, I will close this issue.

**Comment by professorf** [comment]
User interfaces look really nice Sadaf! You're ready for implementation.
